#ifndef MCAL_MEXTI_MEXTI_CONFIG_H_
#define MCAL_MEXTI_MEXTI_CONFIG_H_

#include "MEXTI_Private.h"
#include "MEXTI_Interface.h"
/*
 * 1-MEXTI_LOW_LEVEL
 * 2-MEXTI_ANY_LOGICAL_CHANGE
 * 3-MEXTI_RISING_EDGE
 * 4-MEXTI_FALLING_EDGE
 */

#define MEXTI_SENSE_CONTROL_STATE MEXTI_LOW_LEVEL


#endif /* MCAL_MEXTI_MEXTI_CONFIG_H_ */
